name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman Game
        uses: abozanona/pacman-contribution-graph@2.4.0
        with:
          github_user_name: logicscienc

      - name: Move generated file
        run: |
          mkdir output
          mv pacman-contribution-graph.svg output/

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: output
          force_orphan: true
